import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildReportOnlyCsp,
  collectInlineScriptHashes,
  withReportingDirectives,
} from "./reportOnlyCsp";
import { CSP_REPORT_PATH, CSP_REPORTING_GROUP } from "./cspReportCollector";

// Build-time glue: reads the emitted HTML, hashes its inline scripts, and writes
// a Netlify `_headers` file carrying a Content-Security-Policy-Report-Only header
// into the publish dir. Runs from VitePress's buildEnd hook so the hashes are
// always derived from the real build output and can never silently drift. The
// enforcing CSP in netlify.toml is left untouched — this is the Report-Only
// rollout step, so a missed hash reports a violation without breaking the page.
// The filesystem seams are parameters so the whole flow is testable in isolation.

// Resolved via fileURLToPath rather than `new URL(...)` directly: a test
// environment (e.g. Vitest's happy-dom) can shadow the global `URL`
// constructor, and Node's `fs` functions reject a URL instance from any
// implementation but its own. `import.meta.url` is a plain string per spec,
// so routing through Node's own fileURLToPath sidesteps the ambient global
// entirely and this stays a plain path both writeReportOnlyHeaders and
// callers like config.test.ts (which exercises the real default) can rely on.
const NETLIFY_CONFIG_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "netlify.toml",
);
// `[^"\n]` so a value can never span lines and inject extra `_headers` rules.
const ENFORCING_CSP_PATTERN =
  /^\s*Content-Security-Policy\s*=\s*"([^"\n]*)"/gim;
const FILE_NOT_FOUND_CODE = "ENOENT";

const HTML_EXTENSION = ".html";
const HEADERS_FILE_NAME = "_headers";
const HEADERS_PATH_GLOB = "/*";
const REPORT_ONLY_HEADER_NAME = "Content-Security-Policy-Report-Only";
// Names the collector the `report-to` directive delivers to (Reporting API).
const REPORTING_ENDPOINTS_HEADER_NAME = "Reporting-Endpoints";
// Both headers this script generates. A hand-written copy of either would ship a
// second, conflicting value for the same path, so guard against both.
const GENERATED_HEADER_NAMES = [
  REPORT_ONLY_HEADER_NAME,
  REPORTING_ENDPOINTS_HEADER_NAME,
];
// Escapes a header name for use inside the conflict-line RegExp below — none
// of GENERATED_HEADER_NAMES need it today, but a caller-supplied extra header
// name (see `extraGlobalHeaderLines`) is not guaranteed to be regex-safe.
function escapeForRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Matches any of the given header names only as their own `_headers` line, so
// the name appearing in a comment in a hand-written file doesn't trip the
// conflict guard.
function conflictHeaderLinePattern(headerNames: string[]) {
  return new RegExp(
    `^\\s*(?:${headerNames.map(escapeForRegExp).join("|")})\\s*:`,
    "im",
  );
}

// A single header comfortably under the ~8 KB limit CDNs and origins enforce; the
// build fails loud here rather than letting Netlify truncate or reject at serve.
const MAX_HEADER_BYTES = 8000;

// Marks the block this script owns so a rebuild into a non-emptied publish dir
// replaces its own previous output instead of stacking a second, stale policy.
const GENERATED_MARKER = "# generated by .vitepress/csp — do not edit";

async function readHtmlDocuments(outDir: string) {
  const entries = await readdir(outDir, {
    recursive: true,
    withFileTypes: true,
  });
  const htmlFiles = entries.filter(
    (entry) => entry.isFile() && entry.name.endsWith(HTML_EXTENSION),
  );
  // `parentPath` (Node 20.12+/21.4+) is guaranteed: .nvmrc pins Node 24 and a
  // test keeps it the single source of truth.
  return Promise.all(
    htmlFiles.map((entry) =>
      readFile(join(entry.parentPath, entry.name), "utf8"),
    ),
  );
}

async function readEnforcingCsp(netlifyConfigPath: string | URL) {
  const netlifyConfig = await readFile(netlifyConfigPath, "utf8");
  const matches = [...netlifyConfig.matchAll(ENFORCING_CSP_PATTERN)];
  if (matches.length === 0 || !matches[0][1].trim()) {
    throw new Error(
      "CSP Report-Only: could not read the enforcing Content-Security-Policy from netlify.toml",
    );
  }
  if (matches.length > 1) {
    throw new Error(
      "CSP Report-Only: netlify.toml declares multiple Content-Security-Policy headers; cannot decide which one the Report-Only header should mirror",
    );
  }
  return matches[0][1].trim().replace(/\s+/g, " ");
}

function isFileNotFound(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as { code?: string }).code === FILE_NOT_FOUND_CODE
  );
}

async function readExistingHeaders(headersPath: string) {
  try {
    return await readFile(headersPath, "utf8");
  } catch (error) {
    if (isFileNotFound(error)) {
      return "";
    }
    throw error;
  }
}

// Strip this script's own previous block, then keep any remaining hand-written
// `_headers` (VitePress copies public/_headers into the publish dir). A leftover
// copy of any header this call is about to generate — the two CSP headers plus
// whatever `extraGlobalHeaderLines` names — would ship two conflicting values
// for the same path, so fail loud rather than merge it.
function handWrittenHeaders(
  existingHeaders: string,
  conflictHeaderNames: string[],
) {
  const markerIndex = existingHeaders.indexOf(GENERATED_MARKER);
  const withoutGenerated = (
    markerIndex === -1 ? existingHeaders : existingHeaders.slice(0, markerIndex)
  ).trim();
  if (conflictHeaderLinePattern(conflictHeaderNames).test(withoutGenerated)) {
    throw new Error(
      `CSP Report-Only: ${HEADERS_FILE_NAME} already defines one of ${conflictHeaderNames.join(", ")}; refusing to ship two conflicting policies`,
    );
  }
  return withoutGenerated;
}

// The `report-to` group in the CSP resolves through this header, so the two
// ship together under the same path glob.
function reportingEndpointsHeaderValue() {
  return `${CSP_REPORTING_GROUP}="${CSP_REPORT_PATH}"`;
}

// A single `Name: value` pair with no line break, mirroring the `[^"\n]` CSP
// guard above: an extra header line is interpolated into the `_headers` file
// verbatim, so an embedded newline could inject a second path block and a
// value with no name could ship a malformed rule Netlify silently drops.
// `[ \t]*` (not `\s*`) between the colon and the value: `\s` also matches
// `\n`/`\r`, which would let a single embedded newline slip past the
// `[^\r\n]+` value guard by having the separator itself absorb it. The value
// itself starts with `\S` (not `[^\r\n]+` right away) so the optional
// leading whitespace can't be handed back to satisfy the value on a
// whitespace-only payload like `"X-Robots-Tag: "`, which Netlify would
// silently drop as a malformed rule.
const EXTRA_HEADER_LINE_PATTERN = /^[\w-]+:[ \t]*\S[^\r\n]*$/;

function assertWellFormedExtraHeaderLines(extraGlobalHeaderLines: string[]) {
  const malformed = extraGlobalHeaderLines.filter(
    (line) => !EXTRA_HEADER_LINE_PATTERN.test(line),
  );
  if (malformed.length === 0) {
    return;
  }
  throw new Error(
    `CSP Report-Only: refusing to write malformed extra header line(s): ${malformed.map((line) => JSON.stringify(line)).join(", ")}`,
  );
}

// Well-formedness (assertWellFormedExtraHeaderLines) guarantees a colon, so
// this always finds one.
function extraHeaderLineName(line: string) {
  return line.slice(0, line.indexOf(":")).trim();
}

// A caller passing one of this module's own header names as an extra line
// would silently ship it twice in the same generated block — catch that
// before touching the filesystem, the same way a hand-written duplicate is
// caught below via handWrittenHeaders.
function assertNoReservedHeaderNameCollision(extraHeaderNames: string[]) {
  const collisions = extraHeaderNames.filter((name) =>
    GENERATED_HEADER_NAMES.some(
      (reserved) => reserved.toLowerCase() === name.toLowerCase(),
    ),
  );
  if (collisions.length === 0) {
    return;
  }
  throw new Error(
    `CSP Report-Only: extra header line(s) collide with a header this module already generates: ${collisions.join(", ")}`,
  );
}

// `extraGlobalHeaderLines` lets a caller (see .vitepress/robots) fold an
// unrelated `/*` header, such as a context-gated noindex, into this same
// block instead of writing a second `/*` block — Netlify's behaviour for two
// blocks declaring the same path is undocumented, so this file owns the one
// `/*` block that ships.
function formatGeneratedBlock(
  reportOnlyCsp: string,
  extraGlobalHeaderLines: string[],
) {
  return [
    GENERATED_MARKER,
    HEADERS_PATH_GLOB,
    `  ${REPORT_ONLY_HEADER_NAME}: ${reportOnlyCsp}`,
    `  ${REPORTING_ENDPOINTS_HEADER_NAME}: ${reportingEndpointsHeaderValue()}`,
    ...extraGlobalHeaderLines.map((line) => `  ${line}`),
    "",
  ].join("\n");
}

function mergeHeaders(handWritten: string, generatedBlock: string) {
  if (!handWritten) {
    return generatedBlock;
  }
  return `${handWritten}\n\n${generatedBlock}`;
}

export async function writeReportOnlyHeaders(
  outDir: string,
  netlifyConfigPath: string | URL = NETLIFY_CONFIG_PATH,
  extraGlobalHeaderLines: string[] = [],
) {
  // Caller-supplied and known up front, so fail before the expensive work
  // below (HTML scan, hashing, netlify.toml read) rather than after it.
  assertWellFormedExtraHeaderLines(extraGlobalHeaderLines);
  const extraHeaderNames = extraGlobalHeaderLines.map(extraHeaderLineName);
  assertNoReservedHeaderNameCollision(extraHeaderNames);
  const htmlDocuments = await readHtmlDocuments(outDir);
  const scriptHashes = collectInlineScriptHashes(htmlDocuments);
  if (scriptHashes.length === 0) {
    throw new Error(
      "CSP Report-Only: no executable inline scripts found in the build output; refusing to emit a script-src that would silently mismatch",
    );
  }
  const reportOnlyCsp = withReportingDirectives(
    buildReportOnlyCsp(await readEnforcingCsp(netlifyConfigPath), scriptHashes),
    CSP_REPORTING_GROUP,
    CSP_REPORT_PATH,
  );
  if (reportOnlyCsp.length > MAX_HEADER_BYTES) {
    throw new Error(
      `CSP Report-Only: header is ${reportOnlyCsp.length} bytes from ${scriptHashes.length} inline-script hashes, over the ${MAX_HEADER_BYTES}-byte limit; switch to per-path rules`,
    );
  }
  const headersPath = join(outDir, HEADERS_FILE_NAME);
  const handWritten = handWrittenHeaders(
    await readExistingHeaders(headersPath),
    [...GENERATED_HEADER_NAMES, ...extraHeaderNames],
  );
  await writeFile(
    headersPath,
    mergeHeaders(
      handWritten,
      formatGeneratedBlock(reportOnlyCsp, extraGlobalHeaderLines),
    ),
    "utf8",
  );
}
