import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { buildReportOnlyCsp, collectInlineScriptHashes } from "./reportOnlyCsp";

// Build-time glue: reads the emitted HTML, hashes its inline scripts, and writes
// a Netlify `_headers` file carrying a Content-Security-Policy-Report-Only header
// into the publish dir. Runs from VitePress's buildEnd hook so the hashes are
// always derived from the real build output and can never silently drift. The
// enforcing CSP in netlify.toml is left untouched — this is the Report-Only
// rollout step, so a missed hash reports a violation without breaking the page.
// The filesystem seams are parameters so the whole flow is testable in isolation.

const NETLIFY_CONFIG_URL = new URL("../../netlify.toml", import.meta.url);
const ENFORCING_CSP_PATTERN = /^\s*Content-Security-Policy\s*=\s*"([^"]*)"/gim;
const FILE_NOT_FOUND_CODE = "ENOENT";

const HTML_EXTENSION = ".html";
const HEADERS_FILE_NAME = "_headers";
const HEADERS_PATH_GLOB = "/*";
const REPORT_ONLY_HEADER_NAME = "Content-Security-Policy-Report-Only";

// Marks the block this script owns so a rebuild into a non-emptied publish dir
// replaces its own previous output instead of stacking a second, stale policy.
const GENERATED_MARKER = "# generated by .vitepress/csp — do not edit";
const GENERATED_BLOCK_PATTERN = new RegExp(`\\n*${GENERATED_MARKER}[\\s\\S]*$`);

async function readHtmlDocuments(outDir: string) {
  const entries = await readdir(outDir, {
    recursive: true,
    withFileTypes: true,
  });
  const htmlFiles = entries.filter(
    (entry) => entry.isFile() && entry.name.endsWith(HTML_EXTENSION),
  );
  // `parentPath` (Node 20.12+/21.4+) is guaranteed: .nvmrc pins Node 24 and a
  // test keeps it the single source of truth.
  return Promise.all(
    htmlFiles.map((entry) =>
      readFile(join(entry.parentPath, entry.name), "utf8"),
    ),
  );
}

async function readEnforcingCsp(netlifyConfigPath: string | URL) {
  const netlifyConfig = await readFile(netlifyConfigPath, "utf8");
  const matches = [...netlifyConfig.matchAll(ENFORCING_CSP_PATTERN)];
  if (matches.length === 0 || !matches[0][1].trim()) {
    throw new Error(
      "CSP Report-Only: could not read the enforcing Content-Security-Policy from netlify.toml",
    );
  }
  if (matches.length > 1) {
    throw new Error(
      "CSP Report-Only: netlify.toml declares multiple Content-Security-Policy headers; cannot decide which one the Report-Only header should mirror",
    );
  }
  return matches[0][1].trim();
}

function isFileNotFound(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as { code?: string }).code === FILE_NOT_FOUND_CODE
  );
}

async function readExistingHeaders(headersPath: string) {
  try {
    return await readFile(headersPath, "utf8");
  } catch (error) {
    if (isFileNotFound(error)) {
      return "";
    }
    throw error;
  }
}

// Strip this script's own previous block, then keep any remaining hand-written
// `_headers` (VitePress copies public/_headers into the publish dir). A leftover
// Report-Only header from a hand-written file would ship two conflicting
// policies, so fail loud rather than merge it.
function handWrittenHeaders(existingHeaders: string) {
  const withoutGenerated = existingHeaders
    .replace(GENERATED_BLOCK_PATTERN, "")
    .trim();
  if (withoutGenerated.includes(REPORT_ONLY_HEADER_NAME)) {
    throw new Error(
      `CSP Report-Only: ${HEADERS_FILE_NAME} already defines a ${REPORT_ONLY_HEADER_NAME} header; refusing to ship two conflicting policies`,
    );
  }
  return withoutGenerated;
}

function formatGeneratedBlock(reportOnlyCsp: string) {
  return `${GENERATED_MARKER}\n${HEADERS_PATH_GLOB}\n  ${REPORT_ONLY_HEADER_NAME}: ${reportOnlyCsp}\n`;
}

function mergeHeaders(handWritten: string, generatedBlock: string) {
  if (!handWritten) {
    return generatedBlock;
  }
  return `${handWritten}\n\n${generatedBlock}`;
}

export async function writeReportOnlyHeaders(
  outDir: string,
  netlifyConfigPath: string | URL = NETLIFY_CONFIG_URL,
) {
  const htmlDocuments = await readHtmlDocuments(outDir);
  const scriptHashes = collectInlineScriptHashes(htmlDocuments);
  if (scriptHashes.length === 0) {
    throw new Error(
      "CSP Report-Only: no executable inline scripts found in the build output; refusing to emit a script-src that would silently mismatch",
    );
  }
  const reportOnlyCsp = buildReportOnlyCsp(
    await readEnforcingCsp(netlifyConfigPath),
    scriptHashes,
  );
  const headersPath = join(outDir, HEADERS_FILE_NAME);
  const handWritten = handWrittenHeaders(
    await readExistingHeaders(headersPath),
  );
  await writeFile(
    headersPath,
    mergeHeaders(handWritten, formatGeneratedBlock(reportOnlyCsp)),
    "utf8",
  );
}
