import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  buildReportOnlyCsp,
  collectInlineScriptHashes,
  withReportingDirectives,
} from "./reportOnlyCsp";
import { CSP_REPORT_PATH, CSP_REPORTING_GROUP } from "./cspReportCollector";

// Build-time glue: reads the emitted HTML, hashes its inline scripts, and writes
// a Netlify `_headers` file carrying a Content-Security-Policy-Report-Only header
// into the publish dir. Runs from VitePress's buildEnd hook so the hashes are
// always derived from the real build output and can never silently drift. The
// enforcing CSP in netlify.toml is left untouched — this is the Report-Only
// rollout step, so a missed hash reports a violation without breaking the page.
// The filesystem seams are parameters so the whole flow is testable in isolation.

const NETLIFY_CONFIG_URL = new URL("../../netlify.toml", import.meta.url);
// `[^"\n]` so a value can never span lines and inject extra `_headers` rules.
const ENFORCING_CSP_PATTERN =
  /^\s*Content-Security-Policy\s*=\s*"([^"\n]*)"/gim;
const FILE_NOT_FOUND_CODE = "ENOENT";

const HTML_EXTENSION = ".html";
const HEADERS_FILE_NAME = "_headers";
const HEADERS_PATH_GLOB = "/*";
const REPORT_ONLY_HEADER_NAME = "Content-Security-Policy-Report-Only";
// Names the collector the `report-to` directive delivers to (Reporting API).
const REPORTING_ENDPOINTS_HEADER_NAME = "Reporting-Endpoints";
// Matches the header only as its own `_headers` line, so the name appearing in a
// comment in a hand-written file doesn't trip the conflict guard.
const REPORT_ONLY_HEADER_LINE = new RegExp(
  `^\\s*${REPORT_ONLY_HEADER_NAME}\\s*:`,
  "m",
);

// A single header comfortably under the ~8 KB limit CDNs and origins enforce; the
// build fails loud here rather than letting Netlify truncate or reject at serve.
const MAX_HEADER_BYTES = 8000;

// Marks the block this script owns so a rebuild into a non-emptied publish dir
// replaces its own previous output instead of stacking a second, stale policy.
const GENERATED_MARKER = "# generated by .vitepress/csp — do not edit";

async function readHtmlDocuments(outDir: string) {
  const entries = await readdir(outDir, {
    recursive: true,
    withFileTypes: true,
  });
  const htmlFiles = entries.filter(
    (entry) => entry.isFile() && entry.name.endsWith(HTML_EXTENSION),
  );
  // `parentPath` (Node 20.12+/21.4+) is guaranteed: .nvmrc pins Node 24 and a
  // test keeps it the single source of truth.
  return Promise.all(
    htmlFiles.map((entry) =>
      readFile(join(entry.parentPath, entry.name), "utf8"),
    ),
  );
}

async function readEnforcingCsp(netlifyConfigPath: string | URL) {
  const netlifyConfig = await readFile(netlifyConfigPath, "utf8");
  const matches = [...netlifyConfig.matchAll(ENFORCING_CSP_PATTERN)];
  if (matches.length === 0 || !matches[0][1].trim()) {
    throw new Error(
      "CSP Report-Only: could not read the enforcing Content-Security-Policy from netlify.toml",
    );
  }
  if (matches.length > 1) {
    throw new Error(
      "CSP Report-Only: netlify.toml declares multiple Content-Security-Policy headers; cannot decide which one the Report-Only header should mirror",
    );
  }
  return matches[0][1].trim().replace(/\s+/g, " ");
}

function isFileNotFound(error: unknown) {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as { code?: string }).code === FILE_NOT_FOUND_CODE
  );
}

async function readExistingHeaders(headersPath: string) {
  try {
    return await readFile(headersPath, "utf8");
  } catch (error) {
    if (isFileNotFound(error)) {
      return "";
    }
    throw error;
  }
}

// Strip this script's own previous block, then keep any remaining hand-written
// `_headers` (VitePress copies public/_headers into the publish dir). A leftover
// Report-Only header from a hand-written file would ship two conflicting
// policies, so fail loud rather than merge it.
function handWrittenHeaders(existingHeaders: string) {
  const markerIndex = existingHeaders.indexOf(GENERATED_MARKER);
  const withoutGenerated = (
    markerIndex === -1 ? existingHeaders : existingHeaders.slice(0, markerIndex)
  ).trim();
  if (REPORT_ONLY_HEADER_LINE.test(withoutGenerated)) {
    throw new Error(
      `CSP Report-Only: ${HEADERS_FILE_NAME} already defines a ${REPORT_ONLY_HEADER_NAME} header; refusing to ship two conflicting policies`,
    );
  }
  return withoutGenerated;
}

// The `report-to` group in the CSP resolves through this header, so the two
// ship together under the same path glob.
function reportingEndpointsHeaderValue() {
  return `${CSP_REPORTING_GROUP}="${CSP_REPORT_PATH}"`;
}

function formatGeneratedBlock(reportOnlyCsp: string) {
  return [
    GENERATED_MARKER,
    HEADERS_PATH_GLOB,
    `  ${REPORT_ONLY_HEADER_NAME}: ${reportOnlyCsp}`,
    `  ${REPORTING_ENDPOINTS_HEADER_NAME}: ${reportingEndpointsHeaderValue()}`,
    "",
  ].join("\n");
}

function mergeHeaders(handWritten: string, generatedBlock: string) {
  if (!handWritten) {
    return generatedBlock;
  }
  return `${handWritten}\n\n${generatedBlock}`;
}

export async function writeReportOnlyHeaders(
  outDir: string,
  netlifyConfigPath: string | URL = NETLIFY_CONFIG_URL,
) {
  const htmlDocuments = await readHtmlDocuments(outDir);
  const scriptHashes = collectInlineScriptHashes(htmlDocuments);
  if (scriptHashes.length === 0) {
    throw new Error(
      "CSP Report-Only: no executable inline scripts found in the build output; refusing to emit a script-src that would silently mismatch",
    );
  }
  const reportOnlyCsp = withReportingDirectives(
    buildReportOnlyCsp(await readEnforcingCsp(netlifyConfigPath), scriptHashes),
    CSP_REPORTING_GROUP,
    CSP_REPORT_PATH,
  );
  if (reportOnlyCsp.length > MAX_HEADER_BYTES) {
    throw new Error(
      `CSP Report-Only: header is ${reportOnlyCsp.length} bytes from ${scriptHashes.length} inline-script hashes, over the ${MAX_HEADER_BYTES}-byte limit; switch to per-path rules`,
    );
  }
  const headersPath = join(outDir, HEADERS_FILE_NAME);
  const handWritten = handWrittenHeaders(
    await readExistingHeaders(headersPath),
  );
  await writeFile(
    headersPath,
    mergeHeaders(handWritten, formatGeneratedBlock(reportOnlyCsp)),
    "utf8",
  );
}
