import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { writeReportOnlyHeaders } from "../../csp/writeReportOnlyHeaders";

const HEADERS_FILE = "_headers";
const REPORT_ONLY_HEADER_NAME = "Content-Security-Policy-Report-Only";
const ENFORCING_CSP =
  "default-src 'self'; style-src 'self' 'unsafe-inline'; " +
  "script-src 'self' 'unsafe-inline'";
const INLINE_SCRIPT = `<script id="boot">boot()</script>`;
// Mirrors the shipped public/_headers rule for content-hashed build assets.
const IMMUTABLE_ASSET_CACHE_CONTROL =
  "Cache-Control: public, max-age=31536000, immutable";
const IMMUTABLE_ASSET_RULE = `/assets/*\n  ${IMMUTABLE_ASSET_CACHE_CONTROL}\n`;
const NETLIFY_WITH_CSP = `[[headers]]\n  for = "/*"\n  [headers.values]\n    Content-Security-Policy = "${ENFORCING_CSP}"\n`;

let workDir = "";
let outDir = "";
let netlifyConfigPath = "";

function writeOutFile(name: string, contents: string) {
  writeFileSync(join(outDir, name), contents);
}

function writeNetlifyConfig(contents: string) {
  writeFileSync(netlifyConfigPath, contents);
}

function readGeneratedHeaders() {
  return readFileSync(join(outDir, HEADERS_FILE), "utf8");
}

beforeEach(() => {
  workDir = mkdtempSync(join(tmpdir(), "neonpixels-csp-writer-"));
  outDir = join(workDir, "dist");
  netlifyConfigPath = join(workDir, "netlify.toml");
  mkdirSync(outDir, { recursive: true });
});

afterEach(() => {
  rmSync(workDir, { recursive: true, force: true });
});

describe("writeReportOnlyHeaders", () => {
  it("writes a Report-Only header derived from the build's inline scripts", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    expect(headers).toContain(`${REPORT_ONLY_HEADER_NAME}:`);
    expect(headers).toMatch(/script-src 'self' 'sha256-[A-Za-z0-9+/]+=*'/);
    expect(headers).not.toContain("script-src 'self' 'unsafe-inline'");
  });

  it("wires the Report-Only policy to the collector and emits Reporting-Endpoints", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    expect(headers).toContain("report-uri /csp-report");
    expect(headers).toContain("report-to csp-endpoint");
    expect(headers).toContain(
      `Reporting-Endpoints: csp-endpoint="/csp-report"`,
    );
  });

  it("keeps the hand-written immutable /assets/* rule alongside the generated block", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeOutFile(HEADERS_FILE, IMMUTABLE_ASSET_RULE);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    // Assert the whole rule block, not just its two substrings: this pins the
    // path, the two-space indent, and their adjacency, so a normalized indent
    // or a reordered/split block can't green a rule Netlify would ignore.
    expect(headers).toContain(IMMUTABLE_ASSET_RULE.trimEnd());
    expect(headers).toContain(`${REPORT_ONLY_HEADER_NAME}:`);
  });

  it("appends cleanly when the hand-written file has no trailing newline", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeOutFile(HEADERS_FILE, IMMUTABLE_ASSET_RULE.trimEnd());
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    // handWrittenHeaders() trims, so the trailing-newline and no-newline inputs
    // converge downstream; pin the seam (rule immediately followed by the two
    // blank-line-separated generated marker) so this covers the join itself —
    // a dropped separator or removed trim fails here.
    expect(headers).toMatch(
      /\/assets\/\*\n {2}Cache-Control: [^\n]+\n\n# generated by \.vitepress\/csp/,
    );
    expect(headers).toContain(`${REPORT_ONLY_HEADER_NAME}:`);
  });

  it("preserves the hand-written immutable rule on rebuild without stacking or clobbering it", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeOutFile(HEADERS_FILE, IMMUTABLE_ASSET_RULE);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);
    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    expect(headers.split("/assets/*").length - 1).toBe(1);
    expect(headers.split(REPORT_ONLY_HEADER_NAME).length - 1).toBe(1);
    expect(headers).toContain(IMMUTABLE_ASSET_RULE.trimEnd());
  });

  it("replaces its own previous block rather than stacking a second on rebuild", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);
    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    const occurrences = headers.split(REPORT_ONLY_HEADER_NAME).length - 1;
    expect(occurrences).toBe(1);
  });

  it("keeps a single Reporting-Endpoints line across rebuilds", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await writeReportOnlyHeaders(outDir, netlifyConfigPath);
    await writeReportOnlyHeaders(outDir, netlifyConfigPath);

    const headers = readGeneratedHeaders();
    expect(headers.split("Reporting-Endpoints:").length - 1).toBe(1);
  });

  it("throws when a hand-written file already declares a Report-Only header", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeOutFile(
      HEADERS_FILE,
      `/*\n  ${REPORT_ONLY_HEADER_NAME}: default-src 'self'\n`,
    );
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await expect(
      writeReportOnlyHeaders(outDir, netlifyConfigPath),
    ).rejects.toThrow(/two conflicting policies/);
  });

  it("throws when a hand-written file already declares a Reporting-Endpoints header", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeOutFile(
      HEADERS_FILE,
      `/*\n  Reporting-Endpoints: csp-endpoint="https://elsewhere.example"\n`,
    );
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await expect(
      writeReportOnlyHeaders(outDir, netlifyConfigPath),
    ).rejects.toThrow(/two conflicting policies/);
  });

  it("throws when the build output has no executable inline scripts", async () => {
    writeOutFile(
      "index.html",
      `<script src="/app.js"></script><script type="application/ld+json">{}</script>`,
    );
    writeNetlifyConfig(NETLIFY_WITH_CSP);

    await expect(
      writeReportOnlyHeaders(outDir, netlifyConfigPath),
    ).rejects.toThrow(/no executable inline scripts/);
  });

  it("throws when netlify.toml has no enforcing CSP", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(`[[headers]]\n  for = "/*"\n`);

    await expect(
      writeReportOnlyHeaders(outDir, netlifyConfigPath),
    ).rejects.toThrow(/could not read the enforcing/);
  });

  it("throws when netlify.toml declares more than one enforcing CSP", async () => {
    writeOutFile("index.html", INLINE_SCRIPT);
    writeNetlifyConfig(`${NETLIFY_WITH_CSP}${NETLIFY_WITH_CSP}`);

    await expect(
      writeReportOnlyHeaders(outDir, netlifyConfigPath),
    ).rejects.toThrow(/multiple Content-Security-Policy headers/);
  });

  describe("extraGlobalHeaderLines", () => {
    const NOINDEX_HEADER_LINE = "X-Robots-Tag: noindex";
    const HEADERS_PATH_GLOB = "/*";

    it("folds an extra header line into the same generated /* block", async () => {
      // Seed the hand-written /assets/* rule production always ships, so the
      // path-block count below reflects a realistic file rather than a
      // fixture that happens to omit the one other path in it.
      writeOutFile(HEADERS_FILE, IMMUTABLE_ASSET_RULE);
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await writeReportOnlyHeaders(outDir, netlifyConfigPath, [
        NOINDEX_HEADER_LINE,
      ]);

      const headers = readGeneratedHeaders();
      // Exactly one /* block ships: Netlify's behaviour for two blocks
      // declaring the same path is undocumented, so the noindex line must
      // land inside the existing generated block, not a second one. Counted
      // by exact line match, not substring, so /assets/* (which contains the
      // substring "/*") can't inflate the count.
      const pathGlobLines = headers
        .split("\n")
        .filter((line) => line === HEADERS_PATH_GLOB);
      expect(pathGlobLines).toHaveLength(1);
      expect(headers).toContain(NOINDEX_HEADER_LINE);
      expect(headers).toContain(`${REPORT_ONLY_HEADER_NAME}:`);
    });

    it("does not add the extra line when none is passed", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await writeReportOnlyHeaders(outDir, netlifyConfigPath);

      const headers = readGeneratedHeaders();
      expect(headers).not.toContain(NOINDEX_HEADER_LINE);
    });

    it("drops a stale extra line when a later build omits it, instead of leaving it stuck in a reused publish dir", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      // Simulates a deploy-preview build followed by a production build that
      // reuses the same, non-emptied publish dir (e.g. a local rebuild).
      await writeReportOnlyHeaders(outDir, netlifyConfigPath, [
        NOINDEX_HEADER_LINE,
      ]);
      await writeReportOnlyHeaders(outDir, netlifyConfigPath);

      const headers = readGeneratedHeaders();
      expect(headers).not.toContain(NOINDEX_HEADER_LINE);
      expect(headers.split(REPORT_ONLY_HEADER_NAME).length - 1).toBe(1);
    });

    it("throws instead of writing a line that would inject a second _headers block", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, [
          "X-Robots-Tag: noindex\n/evil/*\n  X-Frame-Options: ALLOWALL",
        ]),
      ).rejects.toThrow(/malformed extra header line/);
    });

    it("throws on a single embedded newline, not just a multi-line payload", async () => {
      // `\s*` between the colon and value would let the separator itself
      // absorb one newline, hiding a path-block injection behind a payload
      // that looks single-line at a glance; pin the narrower case directly.
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, [
          "X-Robots-Tag:\n/evil/*",
        ]),
      ).rejects.toThrow(/malformed extra header line/);
    });

    it("throws instead of writing a line with no header name", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, [""]),
      ).rejects.toThrow(/malformed extra header line/);
    });

    it("throws instead of writing a whitespace-only value", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, ["X-Robots-Tag:   "]),
      ).rejects.toThrow(/malformed extra header line/);
    });

    it("throws when an extra line reuses a header name this module already generates", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, [
          `${REPORT_ONLY_HEADER_NAME}: default-src 'none'`,
        ]),
      ).rejects.toThrow(/collide with a header this module already generates/);
    });

    it("throws when a hand-written file already declares the extra line's header", async () => {
      writeOutFile("index.html", INLINE_SCRIPT);
      writeOutFile(HEADERS_FILE, `/*\n  ${NOINDEX_HEADER_LINE}\n`);
      writeNetlifyConfig(NETLIFY_WITH_CSP);

      await expect(
        writeReportOnlyHeaders(outDir, netlifyConfigPath, [
          NOINDEX_HEADER_LINE,
        ]),
      ).rejects.toThrow(/two conflicting policies/);
    });
  });
});
